NumPy es una biblioteca para el lenguaje de programación Python que da soporte para crear vectores y matrices grandes multidimensionales, junto con una gran colección de funciones matemáticas de alto nivel para operar con ellas.

toda la libreria numpy se articula alrededor de una unica estructura de datos: la matriz multidimensional o ndarray (N-dimensional array)
caracteristicas de ndarray:
-Un ndarray puede contener elementos de cualquier tipo
-Todos los elementos de un ndarray deben ser del mismo tipo 
-el tamaño del ndarray se establece en el momento de la implementacion y no puede cambiarse
-Pero la organizacion de esos elementos entre diferentes dimensiones si puede modificarse

In [2]:
import numpy as np

creacion basica de ndarrays:
existen varias formas pero vamos a ver las mas basicas.

In [3]:
#creando un ndarray vacio
#especificando dimensiones
arrayVacio = np.empty((3,2),dtype= np.unicode)
arrayVacio

C:\Users\Facu\AppData\Local\Temp\ipykernel_10252\419114446.py:2: DeprecationWarning: `np.unicode` is a deprecated alias for `np.compat.unicode`. To silence this warning, use `np.compat.unicode` by itself. In the likely event your code does not need to work on Python 2 you can use the builtin `str` for which `np.compat.unicode` is itself an alias. Doing this will not modify any behaviour and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  arrayVacio = np.empty((3,2),dtype= np.unicode)


array([['', ''],
       ['', ''],
       ['', '']], dtype='<U1')

In [4]:
#copiando dimensiones y tipo desde otra estructura
arrayVacioCopia = np.empty_like([1,2,3,4,5])
arrayVacioCopia


array([1435352432,        593,          0,          0,     131074])

creacion de ndarrays de unos

In [5]:
#especificando dimensiones
arrayUnos = np.ones((3,2))
arrayUnos

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [11]:
#copiando dimensiones y tipo de otra estructura
arrayUnosCopia = np.ones_like([1,2,3,4,5])
arrayUnosCopia

array([1, 1, 1, 1, 1])

creacion de ndarrays de ceros


In [13]:
#especificando dimensiones
arrayZeros = np.zeros((2,3))
arrayZeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
#copiando dimensiones y tipo desde otra estructura
arrayZerosCopia = np.zeros_like([1,2,3,4,5])
arrayZerosCopia

array([0, 0, 0, 0, 0])

creacion de un ndarray con la matriz identidad

In [18]:
#en el argumento indicamos la matriz de cuanto queremos en este ejemplo de 3x3
arrayIdentidad = np.identity(3)
arrayIdentidad

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

creacion de un ndarray con unos en una de las diagonales


In [19]:
#cuaddrada con unos en la diagonal principal
arrayIdentidad = np.eye(4)
arrayIdentidad

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
#cuadrada con unos en la diagonal especificada
arrayConSegundaDiagonal = np.eye(4, k=1)
arrayConSegundaDiagonal

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [21]:
#NO cuadrada con unos en la diagonal especificada
arrayNoCuadrada = np.eye(4,3, k=-1)
arrayNoCuadrada

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

creacion de un ndarray cuyos numeros son una secuencia de numeros

In [22]:
#un parametro desde 0(incluido) hasta el parametro indicado (no incluido)
arraySecuencia1 = np.arange(10)
arraySecuencia1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
#dos parametrso desde el primer parametro(incluido) hasta el segundo parametro(no incluido)
arraySecuencia2 = np.arange(5,10)
arraySecuencia2

array([5, 6, 7, 8, 9])

In [24]:
#tres parametros,desde el primer parametro(incluido) hasta el segundo parametro(no incluido) y con saltos del tercer parametro
arraySecuencia3 = np.arange(5,20,2)
arraySecuencia3

array([ 5,  7,  9, 11, 13, 15, 17, 19])

Creacion de un ndarray a partir de una secuencia basica de python

In [26]:
#unidimensional
arrayBasico = np.array([1,2,3,4,5])
arrayBasico
type(arrayBasico)

numpy.ndarray

In [30]:
#multidimensional
arrayBasicoMultidimensional = np.array([[1,2,3,4],[5,6,7,8]])
arrayBasicoMultidimensional

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

TIPOS DE DATOS EN NDARRAY DE NUMPY
    -Enteros con signo: np.int8, np.int16, np.int32, np.int64
    -Enteros sin signo: np.unit8, np.unit16, np.unit32, np.unit64
    -Numeros en coma flotante: np.float16, np.float32, np.float54, np.float128
    -booleans: np.bool
    -objetos: np.object
    -cadenas de caracteres: np.string\,np.unicode\
    -...

Especificacion/casting/conversion de tipos entre ndarrays

In [31]:
arrayInicialEnteros = np.array([1,2,3,4,5], dtype=np.int32)
arrayInicialEnteros

array([1, 2, 3, 4, 5])

In [32]:
#convertir el array inicial que esta en tipo entero a flotante
arrayFloat = np.asarray(arrayInicialEnteros, dtype=np.float64)
arrayFloat

array([1., 2., 3., 4., 5.])

In [34]:
arrayString = np.asarray(arrayFloat, dtype=np.unicode_)
arrayString

array(['1.0', '2.0', '3.0', '4.0', '5.0'], dtype='<U32')

CONSULTA DE LA COMPOSICION DE UN NDARRAT
    -dtype: tipo de contenido del ndarray
    -ndim: numero de dimensiones/ejes del ndarray
    -shape: estructura/forma del ndarray, es decir el numero0 de elementos en cada uno de los ejes/dimensiones
    -size: numero total de elementos en el ndarray

In [36]:
array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [37]:
#tipo de dato (unico)
array.dtype

dtype('int32')

In [38]:
#numero de dimensiones
array.ndim

2

In [39]:
#forma/dimensiones
array.shape

(3, 4)

In [40]:
#numero total de elementos
array.size

12

Opciones aritmeticas entre ndarrays y escalares
esto lo va a hacer en cada uno de los elementos del ndarray, esta es una de las ventajas de numpy, en python sin este modulo tendriamos que hacer un ciclo que haga esa operacion en cada uno de los elementos del array, en cambio aca con numpy se hace solo sin tener que hacer el ciclo que pase por cada uno de los elementos

In [43]:
array1 = np.array([1,2,3,4,5,6])

In [44]:
#suma
array1+5

array([ 6,  7,  8,  9, 10, 11])

In [45]:
#resta
array1 - 2

array([-1,  0,  1,  2,  3,  4])

In [46]:
#multiplicacion
array1*3

array([ 3,  6,  9, 12, 15, 18])

In [47]:
#division
array1 / 2

array([0.5, 1. , 1.5, 2. , 2.5, 3. ])

In [48]:
#division entera
array1 // 2

array([0, 1, 1, 2, 2, 3], dtype=int32)

In [49]:
#potencia
array1 ** 3

array([  1,   8,  27,  64, 125, 216], dtype=int32)

In [51]:
#asignacion con operador
array1 += 1
array1

array([3, 4, 5, 6, 7, 8])

Operaciones aritmeticas entre ndarrays
Importante: los dos terminos de la operacion tienen que ser ndarrays de la mismas dimensiones y forma. Se aplica la operacion elemento a elemento

In [ ]:
array1 = np.array([1,2,3,4,5,6])

In [52]:
#suma (elemento a elemento)
array1 + array1

array([ 6,  8, 10, 12, 14, 16])

In [53]:
#resta (elemento a elemento)
array1 - array1

array([0, 0, 0, 0, 0, 0])

In [54]:
#multiplicacion (elemento a elemento)
array1 * array1

array([ 9, 16, 25, 36, 49, 64])

In [55]:
#division (elemento a elemento)
array1 / array1

array([1., 1., 1., 1., 1., 1.])

In [57]:
#asignacion con operador
array1 += array1
array1

array([12, 16, 20, 24, 28, 32])

In [58]:
#suma de ndarrays de distinto tamaño (error, esta mal)
array2 = np.array([1,2,3,4,5])
array1 + array2

ValueError: operands could not be broadcast together with shapes (6,) (5,) 

indexacion y slicing basico (como recupero y modifico elementos del ndarray), es igual que en paython usando indexacion [a:b:c]

In [60]:
array = np.arange(1,11)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
#indexacion con primer parametro (ver el elemento en esa posicion)
array[2]

3

In [62]:
#indexacion con primero y segundo elemento, desde donde hasta donde ver
array[2:5]

array([3, 4, 5])

In [63]:
#indexacion con tercer parametro(no quiero todos sino ir dando saltos)
array[::3]

array([ 1,  4,  7, 10])

In [65]:
#indexacion con negativos(del fin a principio)
array[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

en ndarrays multidimensionales, existen dos posibles formas de realizar el acceso:
    -mediante indexacion recursiva: array[a:b:c en dim_1][a:b:c en dim_2]...[a:b:c en dim_n]
    -mediante indexacion con comas: array[a:b:c en dim_1, a:b:c en dim2,...,a:b:c en dim_n]

In [66]:
array = np.array([[[1,2,3,4], [5,6,7,8]], [[9,10,11,12], [13,14,15,16]]])
array

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [67]:
#forma de la matriz
array.shape

(2, 2, 4)

In [68]:
#indexacion recursiva primer nivel
array[1]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [69]:
#indexacion recursiva segundo nivel
array[1][0]

array([ 9, 10, 11, 12])

In [70]:
#indexacion recursiva tercer nivel
array[1][0][3]

12

In [71]:
#indexacion recursiva tercer nivel con slice
array[0][0][:2]

array([1, 2])

In [73]:
#indexacion recursiva tercer nivel con slice negativo
array[1][0][::-1]

array([12, 11, 10,  9])

del mismo modo a como en python, se puede utilizar la indexacion/slicing para modificar secciones de un ndarray

In [74]:
array = np.array([[1,2,3,4],[5,6,7,8]])
array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [75]:
#modificacion de una posicion
array[0][1] = 50
array

array([[ 1, 50,  3,  4],
       [ 5,  6,  7,  8]])

In [77]:
#de dons en dos pone 30
array[0][::2] = 30
array

array([[30, 50, 30,  4],
       [ 5,  6,  7,  8]])

indexacion/slicing booleano

In [87]:
personas = np.array(['miguel','pedro','juan','miguel'])
personas

array(['miguel', 'pedro', 'juan', 'miguel'], dtype='<U6')

In [79]:
datos = np.random.randn(4,4)
datos

array([[-0.3110386 ,  0.87816796,  0.11960332,  1.57091874],
       [-0.62520406, -0.31337972,  0.50066505, -0.33307353],
       [ 0.79433868,  0.03036177, -0.30195707, -0.66671549],
       [ 0.25260848, -1.35136907,  0.77858414, -0.71590824]])

In [82]:
#comprobar si es menor a cero
datos < 0

array([[ True, False, False, False],
       [ True,  True, False,  True],
       [False, False,  True,  True],
       [False,  True, False,  True]])

In [80]:
#indexacion/slicing booleano sobre valores. Te da los valores menores a 0
datos[datos<0]

array([-0.3110386 , -0.62520406, -0.31337972, -0.33307353, -0.30195707,
       -0.66671549, -1.35136907, -0.71590824])

In [88]:
#mascara booleana. Pregunta si la matriz personas es igual a miguel en cada una d esus posiciones
personas == 'miguel'

array([ True, False, False,  True])

In [90]:
#indexacion/slicing mediante mascara. 
datos[personas == 'miguel']

array([[-0.3110386 ,  0.87816796,  0.11960332,  1.57091874],
       [ 0.25260848, -1.35136907,  0.77858414, -0.71590824]])

In [91]:
#indexacion/slicing mediante mascara y basico combinado
datos[personas == 'miguel', ::2]

array([[-0.3110386 ,  0.11960332],
       [ 0.25260848,  0.77858414]])

In [92]:
#indexacion/slicing mediante mascara negativo por operador
datos[personas!='miguel'] #la spersonas que no son miguel

array([[-0.62520406, -0.31337972,  0.50066505, -0.33307353],
       [ 0.79433868,  0.03036177, -0.30195707, -0.66671549]])

denuevo podemos hacer indexacion/slicing booleano para realizar modificaciones sobre el contenido de un ndarray

In [93]:
array = np.random.randn(7,4)
array

array([[-0.85687512, -0.16318353, -0.58307791,  2.15040122],
       [-0.07653675, -0.25259254,  1.82679533,  0.54234377],
       [-0.99775766,  0.51291015,  0.52967745,  0.14139362],
       [-0.77373058, -1.94263565, -0.73829955,  3.63150665],
       [-1.33168021, -0.59703714,  1.31786031,  2.55263468],
       [ 0.01683945, -1.1011282 , -1.5948194 , -0.60739852],
       [ 0.11059845,  1.27150335,  1.16875571,  1.09880793]])

In [94]:
#eliminacion de valores negativos mediante slicing
array[array < 0] = 0
array

array([[0.        , 0.        , 0.        , 2.15040122],
       [0.        , 0.        , 1.82679533, 0.54234377],
       [0.        , 0.51291015, 0.52967745, 0.14139362],
       [0.        , 0.        , 0.        , 3.63150665],
       [0.        , 0.        , 1.31786031, 2.55263468],
       [0.01683945, 0.        , 0.        , 0.        ],
       [0.11059845, 1.27150335, 1.16875571, 1.09880793]])

indexacion y slicing basado en secuencia de enteros - fancy indexing

In [95]:
array = np.empty((8,4))
for i in range(8):
    array[i] = i
array

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [96]:
#indexacion/slicing de un conjunto (arbitrario) de elementos
array[[2,5]]

array([[2., 2., 2., 2.],
       [5., 5., 5., 5.]])

In [97]:
#indexacion/slicing de un conjunto(arbitrario) de elementos (indices negativos) empieza a contar por atras
array[[-2,-5]]

array([[6., 6., 6., 6.],
       [3., 3., 3., 3.]])

tambien podemos indexar de manera arbitraria en multiples dimensiones, utilizando para ello, una secuencia de enteros por cada dimension. El resultado sera la combinacion de secuencias

In [98]:
array = np.arange(32).reshape((8,4))
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [99]:
#indexacion/slicing con una secuencia de varios niveles (elemento a elemento)
array[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

transposicion y modificacion de ejes/dimensiones

In [3]:
array = np.arange(15)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
#modificacion de ejes/dimensiones
array2 = array.reshape(3,5)
array2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [7]:
#trasposicion de ejes/dimensiones
array2.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

concatenacion de ndarray
numpy ofrece la posibilidad de combinar ndarrays de dos formas distintas:
    -hstack, column_stack: los elementos del segundo array se añaden a los del primero a lo ancho (como columnas)
    -vstack, row_stack: los elementos del segundo array se añaden a los del primero a lo largo (como filas)

In [9]:
array1 = np.arange(15).reshape(3,5)
array1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [10]:
array2 = np.arange(15,30).reshape(3,5)
array2

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [11]:
#concatenacion horizontal
np.hstack((array1, array2))

array([[ 0,  1,  2,  3,  4, 15, 16, 17, 18, 19],
       [ 5,  6,  7,  8,  9, 20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14, 25, 26, 27, 28, 29]])

In [12]:
#concatenacion vertical
np.vstack((array1, array2))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

DIVISION DE ARRAYS
Al igual que para la concatenacion, NumPy permite dividir los ndarray de tres formas distintas
    -hsplit: division de arrays en n partes 'iguales' por columnas
    -vsplit: division de arrays en n partes 'iguales' por filas
    -split: division de arrays en n partes no simetricas 

In [13]:
array = np.arange(16).reshape(4, 4)
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [14]:
#Division simetrica por columnas
np.hsplit(array,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [15]:
#division simetrica por filas
np.vsplit(array,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [18]:
#division no simetrica
np.split(array,[1,3], axis=1)


[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [20]:
#division no simetrica
np.split(array,[1,3], axis=0)


[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

axis:
valor 0: aplicara la funcion por columnas
valor 1: aplicara la funcion por filas 


In [19]:
array.sum(axis=0)

array([24, 28, 32, 36])

----------------------------------------------------------------------------------------------OPERACIONES SOBRE NDARRAYS------------------------------------------------------------------------------------------------------------

NumPy pone a nuestra disposicion un amplio conjunto de funciunes optimizadas para aplicar sobre ndarrays de forma global evitando asi la necesidad de utilizar bucles (mucho mas costosos)

Operaciones elemento a elemento - Universal functions
El primero de los conjuntos de funciones ofrecido por NumPy son las llamadas 'funciones universales' (o ufuncs) que permiten la realizacion de operaciones elemento a elemento de un array. En funcion del numero de parametros encontramos dos tipos de funciones universales

Funciones Unarias

son aquellas funciones que reciben como parametro un unico array
    - abs, fabs: valor absoluto
    -sqrt: raiz cuadrada 
    -square: potencia al cuadrado(equivalente a array**2)
    -exp: potencia de e.
    -log, log2, log10, log1p: logaritmos en distintas bases
    -sign: signo (+=1, -=-1, 0=0)
    -ceil: techo
    -floor: suelo
    -rint: redondeo al entero mas cercano
    -modf: devuelve dos arrays uno con la parte entera y otro con la fraccionaria
    -isnan: devuleve un array booleano indicando si el valor es NaN o no
    -isfinite, isinf: devuelve un array booleando indicando si el valor es finito o infinito
    -cos, cosh, sin, sinh, tan, tanh: funciones trigonometricas
    -arccos, arccosh, arcsin, arcsinh, arctan, arctanh: funciones trigonometricas inversas
    -logical_not: inverso booleano de todos los valores del array

In [23]:
array = np.array([1,-2,3,-4,-5])
np.abs(array)

array([1, 2, 3, 4, 5])

In [24]:
np.sign(array)

array([ 1, -1,  1, -1, -1])

Funciones Binarias

son aquellas funciones que reciben como parametros dos arrays

    -add: adicion de los elementos de lso dos arrays (equivalente a array1 + array2)
    -subtract: reste de los elementos de los dos arrays (equivalente a array1 - array2)
    -multiply: multiplica los elementos de los dos arrays (equivalente a array1 * array2)
    -divide, floor_divide: divide los elementos de los dos arrays (equivalente a array1 / (o //) array2)
    -power: eleva los elementos del primer array a las potencias del segundo (equivalente a array1**array2)
    -maximun, fmax: calcula el maximo de los dos arrays(elemento a elemento). fmax ignora NaN
    -minimum, fmin: calcula el minimo de los dos arrays (elemento a elemento). fmin ignora NaN
    -mod: calcula el resto de la division de los dos arrays (equivalente a array1 % array2)
    -greater, greater_equal, less, less_equal, equal, not_equal: comparativas sobre los elemnetos de ambos ndarrays (elemento a elemento).
    -logical_and, logical_or: operaciones booleanas sobre los elementos de ambos ndarrays(elemento a elemento)


In [25]:
array1 = np.random.randn(5,5)
array1

array([[ 0.60734411, -1.48111171,  1.10276935, -0.13162243,  0.86685242],
       [-1.06464333,  0.46543212, -0.61160313,  1.1847854 , -0.00178206],
       [ 0.88314672, -0.98923721, -0.08982207, -0.24286471, -0.1683687 ],
       [-0.06957054, -0.48362156,  0.44053109, -0.03548516,  0.23090091],
       [ 0.39714124,  0.36210095, -0.07310191, -0.80457138,  0.36636853]])

In [27]:
array2 = np.random.randn(5,5)
array2

array([[ 1.30468068,  0.65692321, -0.04791463, -0.28040973, -1.16458617],
       [-0.73819497,  1.55494463,  0.07370754,  0.71926199, -0.10924776],
       [-1.2137882 ,  2.55732805,  1.21579655, -0.39145047, -0.13132419],
       [ 0.76593636, -1.09746556, -0.67448323,  0.64952914, -0.6472114 ],
       [-0.78038613, -0.46370681,  0.42181519, -0.15547246,  1.10105034]])

In [28]:
np.minimum(array1, array2)

array([[ 0.60734411, -1.48111171, -0.04791463, -0.28040973, -1.16458617],
       [-1.06464333,  0.46543212, -0.61160313,  0.71926199, -0.10924776],
       [-1.2137882 , -0.98923721, -0.08982207, -0.39145047, -0.1683687 ],
       [-0.06957054, -1.09746556, -0.67448323, -0.03548516, -0.6472114 ],
       [-0.78038613, -0.46370681, -0.07310191, -0.80457138,  0.36636853]])

In [29]:
np.divide(array1, array2)

array([[ 4.65511694e-01, -2.25461924e+00, -2.30152973e+01,
         4.69393219e-01, -7.44343740e-01],
       [ 1.44222513e+00,  2.99323919e-01, -8.29770154e+00,
         1.64722370e+00,  1.63120654e-02],
       [-7.27595405e-01, -3.86824526e-01, -7.38791954e-02,
         6.20422575e-01,  1.28208451e+00],
       [-9.08307003e-02,  4.40671289e-01, -6.53138684e-01,
        -5.46321352e-02, -3.56762736e-01],
       [-5.08903506e-01, -7.80883384e-01, -1.73303178e-01,
         5.17500914e+00,  3.32744574e-01]])

In [30]:
np.floor_divide(array1, array2)

array([[  0.,  -3., -24.,   0.,  -1.],
       [  1.,   0.,  -9.,   1.,   0.],
       [ -1.,  -1.,  -1.,   0.,   1.],
       [ -1.,   0.,  -1.,  -1.,  -1.],
       [ -1.,  -1.,  -1.,   5.,   0.]])

seleccion de elementos de ndarrays en funcion de una condicion

NumPy pone a nuestra disposicion, a travez de la funcion np.where la posibilidad de generar un array de salida a partir de dos de entrada, estableciendo una mascara booleana que indique si (elemento a elemento) debemos enviar a la salida el elemeneto del primer ndarray (valor true) o del segundo (valor false)

In [31]:
array1 = np.random.randn(5,5)
array1

array([[ 1.16526725,  0.46137323, -0.10492509,  1.02169129, -0.19921279],
       [ 1.45117033, -1.00723244, -0.21573575, -0.27505027,  0.65340767],
       [ 0.08438473, -0.87547939,  0.55717936, -0.67333834,  1.40222719],
       [-0.66939359, -1.69750453,  1.0705283 ,  0.39456092,  0.45852583],
       [ 0.28264843, -0.43362363,  0.83978816, -0.11293868,  0.05190595]])

In [32]:
array2 = np.random.randn(5,5)
array2

array([[-0.62141789, -0.61176973,  0.58796892,  1.44507315,  0.40230404],
       [ 0.76152116, -0.29269572,  1.90238538, -2.42663711,  1.47635853],
       [ 1.3398733 , -1.29578912,  1.26922482, -0.88303038, -1.02770984],
       [ 1.86748905,  0.13674499, -1.3360333 ,  1.33315036, -0.08540266],
       [ 0.65621746,  1.15601521,  0.28426652, -0.77389222, -0.18619379]])

In [33]:
#funsion condicional. Va a hacer una comprobacion si array1 es menor que array2 en el caso de que sea menor devuelve array1 en el caso de que sea mayor devuelve array2
np.where(array1 < array2, array1, array2)

array([[-0.62141789, -0.61176973, -0.10492509,  1.02169129, -0.19921279],
       [ 0.76152116, -1.00723244, -0.21573575, -2.42663711,  0.65340767],
       [ 0.08438473, -1.29578912,  0.55717936, -0.88303038, -1.02770984],
       [-0.66939359, -1.69750453, -1.3360333 ,  0.39456092, -0.08540266],
       [ 0.28264843, -0.43362363,  0.28426652, -0.77389222, -0.18619379]])

In [34]:
#anidacion de condiciones. compáramos si array1 es menor que array2, cuando no se cumple devuelve array2, pero si array1 si es mas chico entra al otro where y dice bueno compruebo si array1 es negativo devuelvo un 0 en caso 
#contrario devuelvo array1
np.where(array1 < array2, np.where(array1 < 0, 0, array1), array2)

array([[-0.62141789, -0.61176973,  0.        ,  1.02169129,  0.        ],
       [ 0.76152116,  0.        ,  0.        , -2.42663711,  0.65340767],
       [ 0.08438473, -1.29578912,  0.55717936, -0.88303038, -1.02770984],
       [ 0.        ,  0.        , -1.3360333 ,  0.39456092, -0.08540266],
       [ 0.28264843,  0.        ,  0.28426652, -0.77389222, -0.18619379]])

Funciones matematicas y estadisticas

NumPy ofrece un amplio conjunto de funciones matematicas y estadisticas que se pueden aplicar sobre ndarrays. A continuacion se puede encontrar con los ejemplos mas tipicos (hay alfunas mas que pueden consultarce en la documentacion oficial de NumPy) 
    -sum: suma de elementos
    -mean: media aritmetica de los elementos
    -median: mediana de los elementos
    -std: desviacion estandar de los elementos
    -var: varianza de los elementos
    -min: valor minimo de los elementos
    -max: valor maximo de los elementos
    -argmin: indice del valor minimo
    -argmax: indice del valor maximo
    -cumsum: suma acumulada de los elementos
    -cumprod: producto acumulado de los elementos

Todas estas funciones pueden recibir, ademas del ndarray sobre el que se aplicaran, un segundo parametro llamado axis. Si no se recibe este parametro las funciones se aplicaran sobre el conjunto global de los elementos del ndarray, pero si se incluye, podra tomar dos valores:
    -valor 0: aplicara la funcion por columnas
    -valor 1: aplicara la funcion por filas


In [45]:
array = np.random.randn(5,4)
array

array([[ 0.14111153, -0.7877889 ,  1.58122837, -0.80232436],
       [ 0.66181029, -1.19136003,  1.45509649, -0.29746294],
       [-0.26068019, -0.62825379, -0.35704518,  1.32618608],
       [-0.38604346,  0.1566172 , -1.46637113, -0.5626492 ],
       [ 2.64257044, -1.34105095,  1.02039108,  0.5738295 ]])

In [49]:
#operacion global
np.sum(array)

1.4778108382192734

In [37]:
#operacion por columnas
np.sum(array, axis=0)

array([-1.70890288,  1.77701041, -2.04698209, -0.66646317])

In [38]:
#operacion por filas
np.sum(array, axis=1)

array([ 0.47499134,  0.08885148,  0.35540383, -1.35171517, -2.21286921])

adicionalmente algunas de estas funciones pueden ser utilizadas como "metodos" de los ndarays y no solo como funciones sobre los mismos.En este caso la sintaxis cambiara y se utilizara la notacion "ndarray.funcion()"

In [50]:
array.sum()

1.4778108382192734

In [48]:
np.argmax(array)

16

In [51]:
np.argmin(array)

14

In [52]:
np.cumsum(array)

array([ 0.14111153, -0.64667737,  0.93455099,  0.13222664,  0.79403693,
       -0.3973231 ,  1.05777339,  0.76031045,  0.49963026, -0.12862353,
       -0.48566871,  0.84051736,  0.4544739 ,  0.6110911 , -0.85528003,
       -1.41792923,  1.22464121, -0.11640974,  0.90398134,  1.47781084])

In [53]:
np.cumprod(array)

array([ 0.14111153, -0.1111661 , -0.17577899,  0.14103176,  0.09333627,
       -0.1111971 , -0.16180251,  0.04813025, -0.0125466 ,  0.00788245,
       -0.00281439, -0.00373241,  0.00144087,  0.00022567, -0.00033091,
        0.00018619,  0.00049201, -0.00065981, -0.00067326, -0.00038634])

Operaciones sobre ndarrays booleanos

dado que, internamente, python trata los valores booleanos True como 1 y Flase como 0. es muy sencillo realizar operaciones matematicas sobre estos valores booleanos de forma que se pueden hacer diferentes chequeos por ejemplo: 

In [54]:
array = np.random.randn(5,5)
array

array([[-0.14879873,  0.38243921,  1.44045285,  1.94217801,  0.21582026],
       [-0.78399003, -1.97297209,  0.43108634,  0.45515592, -0.72437529],
       [ 0.3589788 , -0.46846178, -1.03206093,  1.18749974, -0.52134911],
       [ 0.43229642, -0.5342289 ,  0.46199678, -1.09341422, -0.6243643 ],
       [ 1.22679063,  0.54550972,  1.3685346 , -0.58829934,  0.3273265 ]])

In [55]:
#elementos mayores que 0
(array > 0).sum()

14

In [56]:
#elementos menores que la media
(array < array.mean()).sum()

11

NumPy tambien pone a nuestra disposicion dos funciones de chequeo predefinidas sobre ndarrays booleanos:

    -any: para comprobar si alguno de los elementos es true
    -all: para comprobar si todos los elemtos son true

In [57]:
#algunos de los elementos cumple la condicion
(array == 0).any()

False

In [58]:
#todos los elementos cumplen la condicion
((array >= -2) & (array <= 2)).all()

True

Ordenacion de ndarrays

In [60]:
array = np.random.randn(5,5)
array

array([[-0.5391317 ,  0.5455554 ,  0.07413699,  0.9307132 ,  1.15590205],
       [-1.67296006, -0.40877846,  0.27013637, -1.06615626, -0.66131688],
       [-0.81746893, -0.61615154, -0.21148809,  0.48941087, -1.04710292],
       [-1.44470293, -0.77083028,  0.1094273 , -1.82361684, -0.10660786],
       [ 0.63402664,  0.7095392 , -0.09433085, -0.01543269, -1.2582462 ]])

In [62]:
np.sort(array)

array([[-0.5391317 ,  0.07413699,  0.5455554 ,  0.9307132 ,  1.15590205],
       [-1.67296006, -1.06615626, -0.66131688, -0.40877846,  0.27013637],
       [-1.04710292, -0.81746893, -0.61615154, -0.21148809,  0.48941087],
       [-1.82361684, -1.44470293, -0.77083028, -0.10660786,  0.1094273 ],
       [-1.2582462 , -0.09433085, -0.01543269,  0.63402664,  0.7095392 ]])

In [63]:
np.sort(array, axis=0)

array([[-1.67296006, -0.77083028, -0.21148809, -1.82361684, -1.2582462 ],
       [-1.44470293, -0.61615154, -0.09433085, -1.06615626, -1.04710292],
       [-0.81746893, -0.40877846,  0.07413699, -0.01543269, -0.66131688],
       [-0.5391317 ,  0.5455554 ,  0.1094273 ,  0.48941087, -0.10660786],
       [ 0.63402664,  0.7095392 ,  0.27013637,  0.9307132 ,  1.15590205]])

Funciones de conjunto

NumPy permite realizar tratamierntos sobre un ndarray asuminedo que el total de los elementos del mismo forman un conjunto

    -unique: calcula el conjunto unico de elementos sin duplicados
    -intersect1d: calcula la interseccion de los elementos de dos arrays 
    -union1d: calcula la union de los elementos de dos arrays 
    -in1d: calcula un array booleano que indica si cada elemento del primer array esta contenido en el segundo
    -setdiff1d: calcula la diferencia entre ambos conjuntos
    -setxor1d: calcula la diferencia simetrica entre ambos conjutos

In [65]:
array1 = np.array([6,0,0,0,3,2,5,6])
array1

array([6, 0, 0, 0, 3, 2, 5, 6])

In [66]:
array2 = np.array([7,4,3,1,2,6,5])
array2

array([7, 4, 3, 1, 2, 6, 5])

In [67]:
np.unique(array1)

array([0, 2, 3, 5, 6])

In [68]:
np.union1d(array1,array2)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [69]:
np.in1d(array1, array2)

array([ True, False, False, False,  True,  True,  True,  True])